context:
  version: "2.60.3"

package:
  name: langfuse-python
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/langfuse/langfuse-${{ version }}.tar.gz
    sha256: 171c0caf07a26282bd0403c6c15886ef1f447def42d6570684c94d6d9ae61d6e

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - release = scripts.release:main
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - httpx >=0.15.4,<1.0
    - pydantic >=1.10.7,<3.0
    - backoff >=1.10.0
    - wrapt >=1.14,<2.0
    - packaging >=23.2,<25.0
    - idna >=3.7,<4.0
    - anyio >=4.4.0,<5.0.0
    - requests >=2,<3

tests:
  - python:
      imports:
        - langfuse
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: A client library for accessing langfuse
  homepage: https://github.com/langfuse/langfuse-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
