context:
  version: "3.1.2"

package:
  name: langfuse-python
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/langfuse/langfuse-${{ version }}.tar.gz
    sha256: 1caaf02ce51ab327ba8cc39ca42f719924849d5f0127b2801705c6993953ff41

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - release = scripts.release:main
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - httpx >=0.15.4,<1.0
    - pydantic >=1.10.7,<3.0
    - backoff >=1.10.0
    - wrapt >=1.14,<2.0
    - packaging >=23.2,<25.0
    - idna >=3.7,<4.0
    - anyio >=4.4.0,<5.0.0
    - requests >=2,<3
    - opentelemetry-api >=1.33.1,<2
    - opentelemetry-sdk >=1.33.1,<2
    - opentelemetry-exporter-otlp >=1.33.1,<2

tests:
  - python:
      imports:
        - langfuse
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A client library for accessing langfuse
  homepage: https://github.com/langfuse/langfuse-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
